# -*- coding: utf-8 -*-
"""Facial expression VIDEO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fLItY0WxsA4uaNYHX98_5SpB4TdSUkrf
"""

from keras.models import load_model
import cv2
import numpy as np

model = load_model('model-007.model')

face_clsfr=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

source=cv2.VideoCapture(0)

labels_dict={0: 'angry', 1: 'disgust', 2: 'fear', 3: 'happy', 4: 'neutral', 5: 'sad', 6: 'surprise'}
color_dict={0:(0,255,0),1:(0,0,255),2:(255, 255, 0),3:(0, 128, 0), 4:(250, 128, 114), 5:(128, 128, 0), 6:(255,0,0)}

while(True):

    ret,img=source.read()
    gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces=face_clsfr.detectMultiScale(gray,1.3,5)  

    for x,y,w,h in faces:
    
        face_img=gray[y:y+w,x:x+w]
        resized=cv2.resize(face_img,(48,48))
        normalized=resized/255.0
        reshaped=np.reshape(normalized,(1,48,48,1))
        result=model.predict(reshaped)

        label=np.argmax(result,axis=1)[0]
      
        cv2.rectangle(img,(x,y),(x+w,y+h),color_dict[label],2)
        cv2.rectangle(img,(x,y-40),(x+w,y),color_dict[label],-1)
        cv2.putText(img, labels_dict[label], (x, y-10),cv2.FONT_HERSHEY_SIMPLEX,0.8,(255,255,255),2)
        
        
    cv2.imshow('FACIAL DETECTION',img)
    key=cv2.waitKey(1)
    
    #press esc to escape
    if(key==27):
        break
        
cv2.destroyAllWindows()
source.release()

